Repository BCSDLab/KOIN_iOS, pull requests merged in 2024-12, with the labels that each got.

#99 refactor: 네비게이션 바마다 backbutton을 만들어줘야 하는 이슈 해결
  Koin/Apps/AppDelegate.swift
  Koin/Core/Extensions/UIViewController+NavigationBarStyle.swift
  Koin/Core/View/CustomViewController.swift
  Koin/Presentation/Bus/BusDetailViewController.swift
  Koin/Presentation/ChangeMyProfile/ChangeMyProfileViewController.swift
  Koin/Presentation/ChangePassword/ChangePasswordViewController.swift
  Koin/Presentation/Dining/DiningViewController.swift
  Koin/Presentation/DiningNotice/DiningNoticeViewController.swift
  Koin/Presentation/FacilityInfo/FacilityInfoViewController.swift
  Koin/Presentation/FindPassword/FindPasswordViewController.swift
  Koin/Presentation/Land/LandViewController.swift
  Koin/Presentation/LandDetail/LandDetailViewController.swift
  Koin/Presentation/Login/LoginViewController.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewController.swift
  Koin/Presentation/MyProfile/MyProfileViewController.swift
  Koin/Presentation/Noti/NotiViewController.swift
  Koin/Presentation/NoticeData/NoticeDataViewController.swift
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewController.swift
  Koin/Presentation/Policy/PolicyViewController.swift
  Koin/Presentation/Register/RegisterViewController.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
  Koin/Presentation/Settings/SettingsViewController.swift
  Koin/Presentation/Shop/ShopViewControllerA.swift
  Koin/Presentation/Shop/ShopViewControllerB.swift
  Koin/Presentation/ShopData/ShopDataViewController.swift
  Koin/Presentation/ShopReview/ShopReviewViewController.swift
  Koin/Presentation/ShopReviewReport/ShopReviewReportViewController.swift
  koin.xcodeproj/project.pbxproj
Labels: enhancement, design

#98 fix: 앱이 꺼진 상태에서는 푸시알림 이동이 처리되지 않던 버그 수정
  Koin/Apps/AppDelegate.swift
  Koin/Apps/NotificationHandler.swift
  Koin/Apps/SceneDelegate.swift
  Koin/Core/Extensions/UIViewController+NavigationBarStyle.swift
  Koin/Core/View/CustomViewController.swift
  Koin/Presentation/Bus/BusDetailViewController.swift
  Koin/Presentation/ChangeMyProfile/ChangeMyProfileViewController.swift
  Koin/Presentation/ChangePassword/ChangePasswordViewController.swift
  Koin/Presentation/Dining/DiningViewController.swift
  Koin/Presentation/DiningNotice/DiningNoticeViewController.swift
  Koin/Presentation/FacilityInfo/FacilityInfoViewController.swift
  Koin/Presentation/FindPassword/FindPasswordViewController.swift
  Koin/Presentation/Home/HomeViewControllerA.swift
  Koin/Presentation/Land/LandViewController.swift
  Koin/Presentation/LandDetail/LandDetailViewController.swift
  Koin/Presentation/Login/LoginViewController.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewController.swift
  Koin/Presentation/MyProfile/MyProfileViewController.swift
  Koin/Presentation/Noti/NotiViewController.swift
  Koin/Presentation/NoticeData/NoticeDataViewController.swift
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewController.swift
  Koin/Presentation/Policy/PolicyViewController.swift
  Koin/Presentation/Register/RegisterViewController.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
  Koin/Presentation/Settings/SettingsViewController.swift
  Koin/Presentation/Shop/ShopViewControllerA.swift
  Koin/Presentation/Shop/ShopViewControllerB.swift
  Koin/Presentation/ShopData/ShopDataViewController.swift
  Koin/Presentation/ShopReview/ShopReviewViewController.swift
  Koin/Presentation/ShopReviewReport/ShopReviewReportViewController.swift
  koin.xcodeproj/project.pbxproj
Labels: bug

#109 fix: 로깅 수정
  Koin/Domain/Model/Log/EventParameter.swift
  Koin/Presentation/Home/HomeViewControllerA.swift
  Koin/Presentation/Home/HomeViewControllerB.swift
  Koin/Presentation/Noti/NotiViewModel.swift
Labels: log

#118 log: 버스 UI 개편 후 로깅
  Koin/Core/View/KoinPickerView.swift
  Koin/Domain/Model/Log/EventParameter.swift
  Koin/Presentation/BusSearch/BusSearchViewController.swift
  Koin/Presentation/BusSearch/BusSearchViewModel.swift
  Koin/Presentation/BusSearch/SubViews/BusAreaSelected/BusAreaSelectdViewController.swift
  Koin/Presentation/BusSearchResult/BusSearchResultViewController.swift
  Koin/Presentation/BusSearchResult/BusSearchResultViewModel.swift
  Koin/Presentation/BusSearchResult/SubViews/BusSearchDatePickerViewController.swift
  Koin/Presentation/BusTimetable/BusTimetableRouteView/BusTimetableRouteCollectionView.swift
  Koin/Presentation/BusTimetable/BusTimetableRouteView/BusTimetableRouteView.swift
  Koin/Presentation/BusTimetable/BusTimetableViewController.swift
  Koin/Presentation/BusTimetable/BusTimetableViewModel.swift
  Koin/Presentation/BusTimetable/ExpressTimetableTableView/ExpressOrCityTimetableTableView.swift
  Koin/Presentation/BusTimetable/ShuttleTimetableTableView/ShuttleTimetableTableView.swift
  Koin/Presentation/BusTimetableData/BusTimetableDataViewController.swift
  Koin/Presentation/BusTimetableData/BusTimetableDataViewModel.swift
  Koin/Presentation/Home/HomeViewController.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
Labels: log

#120 fix: 없어진 공지사항 검색 navigationBarItem 수정
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewController.swift
Labels: bug
