Repository BCSDLab/KOIN_iOS, pull requests merged in 2024-10, with the labels that each got.

#35 chore: my page 디자인 변경
  Koin/Core/Extensions/UIImage+.swift
  Koin/Core/Extensions/UITableView+.swift
  Koin/Core/Extensions/UIViewController+ToastMessage.swift
  Koin/Core/Workers/PasswordValidator.swift
  Koin/Core/Workers/UserInputConfirmer/PasswordConfirmer.swift
  Koin/Data/DTOs/Encodable/User/UserPutRequest.swift
  Koin/Data/Repository/DefaultUserRepository.swift
  Koin/Data/Service/Network/API/UserAPI.swift
  Koin/Data/Service/NetworkService.swift
  Koin/Data/Service/UserService.swift
  Koin/Domain/Model/User/PolicyModel.swift
  Koin/Domain/Repository/UserRepository.swift
  Koin/Domain/UseCase/User/CheckPasswordUseCase.swift
  Koin/Domain/UseCase/User/ModifyUseCase.swift
  Koin/Presentation/Bus/BusDetailViewController.swift
  Koin/Presentation/ChangeMyProfile/ChangeMyProfileViewController.swift
  Koin/Presentation/ChangeMyProfile/ChangeMyProfileViewModel.swift
  Koin/Presentation/ChangePassword/ChangePasswordViewController.swift
  Koin/Presentation/ChangePassword/ChangePasswordViewModel.swift
  Koin/Presentation/ChangePassword/SubViews/CertificationView.swift
  Koin/Presentation/ChangePassword/SubViews/ChangePasswordView.swift
  Koin/Presentation/Dining/DiningViewController.swift
  Koin/Presentation/Land/LandViewController.swift
  Koin/Presentation/Login/LoginViewController.swift
  Koin/Presentation/MyPage/MyPageViewController.swift
  Koin/Presentation/MyPage/MyPageViewModel.swift
  Koin/Presentation/MyProfile/MyProfileViewController.swift
  Koin/Presentation/MyProfile/MyProfileViewModel.swift
  Koin/Presentation/MyProfile/RevokeModalViewController.swift
  Koin/Presentation/Noti/NotiViewController.swift
  Koin/Presentation/Policy/PolicyViewController.swift
  Koin/Presentation/Policy/SubViews/PolicyContentCollectionView/PolicyContentCollectionView.swift
  Koin/Presentation/Policy/SubViews/PolicyContentCollectionView/PolicyContentCollectionViewCell.swift
  Koin/Presentation/Policy/SubViews/PolicyListTableView/PolicyListCollectionViewCell.swift
  Koin/Presentation/Policy/SubViews/PolicyListTableView/PolicyListTableView.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
  Koin/Presentation/Settings/SettingsViewController.swift
  Koin/Presentation/Settings/SettingsViewModel.swift
  Koin/Presentation/Shop/ShopViewController.swift
  Koin/Resources/Assets.xcassets/check.imageset/Contents.json
  Koin/Resources/Assets.xcassets/check.imageset/check.svg
  Koin/Resources/Assets.xcassets/checkGreen.imageset/Contents.json
  Koin/Resources/Assets.xcassets/checkGreen.imageset/checkGreen.svg
  Koin/Resources/Assets.xcassets/chevronRight.imageset/Contents.json
  Koin/Resources/Assets.xcassets/chevronRight.imageset/chevronRight.svg
  Koin/Resources/Assets.xcassets/chevronUp.imageset/Contents.json
  Koin/Resources/Assets.xcassets/chevronUp.imageset/chevronUp.svg
  Koin/Resources/Assets.xcassets/gear.imageset/Contents.json
  Koin/Resources/Assets.xcassets/gear.imageset/gear.svg
  Koin/Resources/Assets.xcassets/topCircle.imageset/Contents.json
  Koin/Resources/Assets.xcassets/topCircle.imageset/topCircle.svg
  Koin/Resources/Assets.xcassets/visibility.imageset/Contents.json
  Koin/Resources/Assets.xcassets/visibility.imageset/visibility.svg
  Koin/Resources/Assets.xcassets/visibilityNon.imageset/Contents.json
  Koin/Resources/Assets.xcassets/visibilityNon.imageset/visibilityNon.svg
  koin.xcodeproj/project.pbxproj
Labels: enhancement, design

#44 feat: 교내 시설물 정보 추가, 코인 공지 추가
  Koin/Domain/Model/NoticeList/NoticeListType.swift
  Koin/Presentation/FacilityInfo/FacilityInfoViewController.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewController.swift
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/NoticeList/TabBar/TabBarCollectionView/TabBarCollectionView.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
  koin.xcodeproj/project.pbxproj
Labels: enhancement, design

#43 log: 캠퍼스 공지사항 로깅
  Koin/Apps/AppDelegate.swift
  Koin/Core/View/LoginModalViewController.swift
  Koin/Data/Repository/GA4AnalyticsRepository.swift
  Koin/Domain/Model/Log/EventParameter.swift
  Koin/Domain/UseCase/NoticeList/AddNotificationKeywordUseCase.swift
  Koin/Presentation/Dining/DiningViewController.swift
  Koin/Presentation/Home/HomeViewController.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewController.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewModel.swift
  Koin/Presentation/NoticeData/HotNoticeArticlesTableView/HotNoticeArticlesTableView.swift
  Koin/Presentation/NoticeData/NoticeDataViewController.swift
  Koin/Presentation/NoticeData/NoticeDataViewModel.swift
  Koin/Presentation/NoticeList/NoticeKeywordCollectionView/NoticeKeywordCollectionView.swift
  Koin/Presentation/NoticeList/NoticeListTableView/NoticeListTableView.swift
  Koin/Presentation/NoticeList/NoticeListTableView/NoticeListTableViewKeyWordCell.swift
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/NoticeList/NoticeListViewModel.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewController.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewModel.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
Labels: log

#55 chore: 학생 운영식당 정보 api 변경에 따른 코드 수정
  Koin/Data/Repository/DefaultDiningRepository.swift
  Koin/Data/Service/DiningService.swift
  Koin/Data/Service/Network/API/DiningAPI.swift
  Koin/Domain/Repository/DiningRepository.swift
  Koin/Domain/UseCase/Dining/FetchCoopShopListUseCase.swift
Labels: bug

#58 fix: 3.3.6 버전 배포 버그 수정
  Koin/Apps/AppDelegate.swift
  Koin/Data/Repository/GA4AnalyticsRepository.swift
  Koin/Domain/Model/Log/EventParameter.swift
  Koin/Domain/Repository/AnalyticsRepository.swift
  Koin/Domain/UseCase/Analytics/LogAnalyticsEventUseCase.swift
  Koin/Domain/UseCase/NoticeList/FetchRecentSearchedWordUseCase.swift
  Koin/Presentation/Dining/DiningViewModel.swift
  Koin/Presentation/Dining/SubViews/CalendarCollectionView/CalendarCollectionView.swift
  Koin/Presentation/Home/HomeViewControllerA.swift
  Koin/Presentation/NoticeSearch/NoticeSearchViewModel.swift
Labels: bug

#64 fix: 저녁 6시반 이후에 파란색 원은 오늘을, 테두리만 파란색 원은 내일을 가리키도록 수정
  Koin/Presentation/Dining/SubViews/CalendarCollectionView/CalendarCollectionView.swift
Labels: bug

#66 feat: 알림 설정에 공지사항 키워드 알림 접근 영역 추가
  Koin/Presentation/Noti/NotiViewController.swift
Labels: enhancement, design
