Repository BCSDLab/KOIN_iOS, pull requests merged in 2025-03, with the labels that each got.

#131 fix: 버스 화면 버그 수정
  Koin/Data/DTOs/Decodable/Bus/CityBusTimetableDTO.swift
  Koin/Data/DTOs/Decodable/Bus/ShuttleBusTimetableDTO.swift
  Koin/Domain/UseCase/Bus/FetchCityBusTimetableUseCase.swift
  Koin/Presentation/BusSearchResult/SubViews/BusSearchResultTableView/BusSearchResultTableViewCell.swift
  Koin/Presentation/BusTimetable/BusTimetableViewModel.swift
  Koin/Presentation/BusTimetableData/BusTimetableDataViewController.swift
  koin.xcodeproj/project.pbxproj
Labels: bug

#137 refactor: Then 라이브러리 적용
  Koin/Presentation/Dining/DiningViewController.swift
  Koin/Presentation/Dining/SubViews/CalendarCollectionView/CalendarCollectionViewCell.swift
  Koin/Presentation/Dining/SubViews/DiningCollectionView/DiningCollecitonFooterView.swift
  Koin/Presentation/Dining/SubViews/DiningCollectionView/DiningCollectionViewCellA.swift
  Koin/Presentation/Dining/SubViews/DiningCollectionView/DiningCollectionViewCellB.swift
  Koin/Presentation/DiningNotice/DiningNoticeViewController.swift
  Koin/Presentation/DiningNotice/SubViews/DiningOperatingTimeCollectionViewCell.swift
  Koin/Presentation/DiningNotice/SubViews/DiningOperatingTimeHeaderView.swift
  Koin/Presentation/FindPassword/FindPasswordViewController.swift
  Koin/Presentation/Home/HomeViewController.swift
  Koin/Presentation/Home/SubViews/CancelableImageView.swift
  Koin/Presentation/Home/SubViews/LogoView.swift
  Koin/Presentation/Home/SubViews/MenuView/MenuBackgronudView.swift
  Koin/Presentation/Home/SubViews/MenuView/MenuCollectionView/MenuCollectionViewCell.swift
  Koin/Presentation/Home/SubViews/MenuView/MenuView.swift
  Koin/Presentation/Home/SubViews/ShopCollectionView/ShopCollectionViewCell.swift
  Koin/Presentation/Land/SubViews/LandCollectionViewCell.swift
  Koin/Presentation/LandDetail/LandDetailViewController.swift
  Koin/Presentation/LandDetail/SubViews/HouseInfoView.swift
  Koin/Presentation/LandDetail/SubViews/LandImageCollectionView/LandImageCollectionViewCell.swift
  Koin/Presentation/LandDetail/SubViews/LandOptionCollectionView/LandOptionCollectionViewCell.swift
  Koin/Presentation/LandDetail/SubViews/LandOptionView.swift
  Koin/Presentation/Login/LoginViewController.swift
  Koin/Presentation/Register/RegisterViewController.swift
  Koin/Presentation/ServiceSelect/ServiceSelectViewController.swift
  Koin/Presentation/ShopData/ShopDataViewControllerA.swift
  Koin/Presentation/ShopData/ShopDataViewControllerB.swift
  Koin/Presentation/ShopData/SubViews/EventListCollectionView/EventListCollectionViewCell.swift
  Koin/Presentation/ShopData/SubViews/GuideLabel.swift
  Koin/Presentation/ShopData/SubViews/MenuImageCollectionView/MenuImageCollectionViewCell.swift
  Koin/Presentation/ShopData/SubViews/MenuListCollectionView/MenuListCollectionViewCell.swift
  Koin/Presentation/ShopData/SubViews/MenuListCollectionView/MenuSectionHeaderView.swift
  Koin/Presentation/ShopData/SubViews/PossibilityLabel.swift
  Koin/Presentation/ShopData/SubViews/ReviewLoginModalViewController.swift
  Koin/Presentation/ShopData/SubViews/ShopDataPageViewControllers/EventListViewController.swift
  Koin/Presentation/ShopData/SubViews/ShopDataPageViewControllers/MenuListViewController.swift
Labels: refactor

#140 log: 로그인하기 팝업 로깅 요청
  Koin/Domain/Model/Log/EventParameter.swift
  Koin/Presentation/ManageNoticeKeyWord/ManageNoticeKeywordViewController.swift
  Koin/Presentation/NoticeList/NoticeListViewController.swift
  Koin/Presentation/ShopData/SubViews/ShopDataPageViewControllers/ReviewListViewController.swift
  Koin/Presentation/ShopData/SubViews/ShopDataPageViewControllers/ReviewListViewModel.swift
Labels: log
